import Head from "next/head";
import { useState } from "react";
import intersection from "../utils/intersection";

type Player = {
  personaname: string;
};

export default function Home() {
  const [playerId, setPlayerId] = useState("tobiaswust");
  const [players, setPlayers] = useState<Player[]>([]);

  function getPlayerData() {
    fetch(`/api/getPlayer?playerId=${playerId}`)
      .then((res) => res.json())
      .then((data) => {
        if (players.find((player) => player.personaname === data.personaname))
          return;
        setPlayers((state) => [...state, data]);
      });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid max-w-md gap-3">
        <input
          type="text"
          value={playerId}
          onChange={(e) => setPlayerId(e.target.value)}
        />
        <button type="button" onClick={getPlayerData}>
          Get Player Data
        </button>
        <h2>Players:</h2>
        <ul>
          {players.map((player) => (
            <li>{player.player.personaname}</li>
          ))}
        </ul>
        <h2>Games:</h2>
        <ul>
          {players.map(
            (player) =>
              player.ownedGames &&
              player.ownedGames.map((game) => <li>{game.details.name}</li>)
          )}
        </ul>
      </main>
    </>
  );
}
